### ISSUE TITLE
🐛 Landing to raw is missing permissions to write to fail location

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/analytical-platform#2266]
### Describe the bug.

Landing to raw is logging that it is moving things to the fail bucket, but the copy doesn't work, so this doesn't happen.

Stacktrace from logs:

```
[ERROR] ClientError: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
Traceback (most recent call last):
  File "/var/task/landing_to_raw.py", line 95, in handler
    s3.copy(
  File "/var/lang/lib/python3.11/site-packages/boto3/s3/inject.py", line 444, in copy
    return future.result()
  File "/var/lang/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/var/lang/lib/python3.11/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/var/lang/lib/python3.11/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/var/lang/lib/python3.11/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/var/lang/lib/python3.11/site-packages/s3transfer/copies.py", line 316, in _main
    client.copy_object(
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
[ERROR] ClientError: An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied Traceback (most recent call last):   File "/var/task/landing_to_raw.py", line 95, in handler     s3.copy(   File "/var/lang/lib/python3.11/site-packages/boto3/s3/inject.py", line 444, in copy     return future.result()   File "/var/lang/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result     return self._coordinator.result()   File "/var/lang/lib/python3.11/site-packages/s3transfer/futures.py", line 266, in result     raise self._exception   File "/var/lang/lib/python3.11/site-packages/s3transfer/tasks.py", line 139, in __call__     return self._execute_main(kwargs)   File "/var/lang/lib/python3.11/site-packages/s3transfer/tasks.py", line 162, in _execute_main     return_value = self._main(**kwargs)   File "/var/lang/lib/python3.11/site-packages/s3transfer/copies.py", line 316, in _main     client.copy_object(   File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 534, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 976, in _make_api_call     raise error_class(parsed_response, operation_name)
```

### To Reproduce

Upload a csv we can't process, e.g. landing/hmpps_pathfinder/v1.0/nominal_notes/

### Expected Behaviour

file should be moved to fail/ in the data bucket

**Comment by mitchdawson1982** [comment]
Initial PR - https://github.com/ministryofjustice/modernisation-platform-environments/pull/4008
